version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.11
  - dependency-name: gatsby
    versions:
    - 3.2.0
